import type { INodeProperties } from 'n8n-workflow';
import { INVOICE_TYPES } from '../../shared/invoiceCatalog';

const notice = (
	name: string,
	text: string,
	show: NonNullable<INodeProperties['displayOptions']>['show'],
): INodeProperties => ({
	displayName: text,
	name,
	type: 'notice',
	default: '',
	displayOptions: { show },
});

const entityDropdown = (show: Record<string, string[]>): INodeProperties => ({
	displayName: 'Entity',
	name: 'entityDataName',
	type: 'resourceLocator',
	default: { mode: 'list', value: '' },
	required: true,
	description: 'Search this account’s entities. Paste an ID only if you already know it (e_…).',
	displayOptions: { show },
	modes: [
		{
			displayName: 'From List',
			name: 'list',
			type: 'list',
			typeOptions: { searchListMethod: 'searchEntities', searchable: true },
		},
		{
			displayName: 'ID',
			name: 'id',
			type: 'string',
			placeholder: 'e_471',
		},
	],
});

export const origamiProperties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'Calendar', value: 'calendar' },
			{ name: 'Communication', value: 'communication' },
			{ name: 'Entity', value: 'entity' },
			{ name: 'File', value: 'file' },
			{ name: 'Invoice', value: 'invoice' },
			{ name: 'Omnichannel', value: 'omnichannel' },
			{ name: 'Record', value: 'record' },
			{ name: 'Repeatable Group', value: 'repeatableGroup' },
		],
		default: 'record',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['entity'] } },
		options: [
			{ name: 'Get Many', value: 'getAll', action: 'List entities', description: 'List entities the API user can access' },
			{ name: 'Get Structure', value: 'getStructure', action: 'Get entity structure', description: 'Field groups, types, and names for an entity' },
		],
		default: 'getAll',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['record'] } },
		options: [
			{ name: 'Archive', value: 'archive', action: 'Archive a record' },
			{ name: 'Create', value: 'create', action: 'Create a record' },
			{ name: 'Delete', value: 'delete', action: 'Hard delete records' },
			{ name: 'Get', value: 'get', action: 'Get a record' },
			{ name: 'Get Form Template', value: 'getFormTemplate', action: 'Get a create template' },
			{ name: 'Get History', value: 'getHistory', action: 'Get record audit history' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many records' },
			{ name: 'Unarchive', value: 'unarchive', action: 'Restore a record' },
			{ name: 'Update', value: 'update', action: 'Update record fields' },
		],
		default: 'getAll',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['repeatableGroup'] } },
		options: [
			{ name: 'Add', value: 'add', action: 'Add a repeatable group row' },
			{ name: 'Remove', value: 'remove', action: 'Remove a repeatable group row' },
		],
		default: 'add',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['file'] } },
		options: [
			{ name: 'Download', value: 'download', action: 'Download a file' },
			{ name: 'Upload', value: 'upload', action: 'Upload a file to a record field' },
		],
		default: 'upload',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['invoice'] } },
		options: [
			{ name: 'Create', value: 'create', action: 'Create an invoice' },
			{ name: 'Get', value: 'get', action: 'Get an invoice' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many invoices' },
			{ name: 'Get Structure', value: 'getStructure', action: 'Get invoice field catalog' },
		],
		default: 'getAll',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['communication'] } },
		options: [
			{ name: 'Send Email', value: 'sendEmail', action: 'Send email' },
			{ name: 'Send Push', value: 'sendPush', action: 'Send a push notification' },
			{ name: 'Send SMS', value: 'sendSms', action: 'Send SMS' },
		],
		default: 'sendEmail',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['omnichannel'] } },
		options: [{ name: 'Ingest Message', value: 'ingest', action: 'Push a message into origami' }],
		default: 'ingest',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['calendar'] } },
		options: [{ name: 'Get View Details', value: 'getViewDetails', action: 'Get calendar view details' }],
		default: 'getViewDetails',
	},

	notice(
		'entityStructureHint',
		'Use Get Structure (or Record → Get Form Template) before Create/Update so field and group names match this account. Do not copy e_* / fld_* from another tenant.',
		{ resource: ['entity'], operation: ['getStructure'] },
	),
	notice(
		'recordReadHint',
		'Paging is skip + limit, not page. Include Archived off sends with_archive=0. Relation and user fields often cannot be filtered on the server.',
		{ resource: ['record'], operation: ['get', 'getAll'] },
	),
	notice(
		'recordWriteHint',
		'Start from Get Structure. Relation fields take the related record _id, not the label. Turn on Force Workflow Async if Origami workflows fail the write.',
		{ resource: ['record'], operation: ['create', 'update'] },
	),
	notice(
		'recordDeleteHint',
		'Delete is permanent. Prefer Archive unless you mean to hard-remove.',
		{ resource: ['record'], operation: ['delete'] },
	),
	notice(
		'invoiceCreateHint',
		'Customer and item IDs must belong to the selected company catalog. Date is DD/MM/YYYY. For tax_receipt and receipt, Cash Amount must equal the items total or Origami rejects the document.',
		{ resource: ['invoice'], operation: ['create'] },
	),
	notice(
		'invoiceTaxHint',
		'tax_invoice / tax_receipt / refund_invoice can provision to the IL Tax Authority when the company is NIS with VAT IDs and a token. Use deal_invoice to draft without allocation.',
		{ resource: ['invoice'], operation: ['create'], invoiceType: ['tax_invoice', 'tax_receipt', 'refund_invoice'] },
	),
	notice(
		'fileUploadHint',
		'Upload sends the binary as multipart field "file", then attaches the returned file id to the record field. Download uses that file id, not the record id.',
		{ resource: ['file'] },
	),
	notice(
		'calendarHint',
		'Start and End are required. An empty range or view returns Origami "no results".',
		{ resource: ['calendar'] },
	),
	notice(
		'smsHint',
		'Sends a real SMS through the account gateway. Use a test number first.',
		{ resource: ['communication'], operation: ['sendSms'] },
	),
	notice(
		'omniHint',
		'Ingest only (no read API). Shape: message_info + properties.app_type (whatsapp, sms, …). Incoming test messages should use sending_type incoming.',
		{ resource: ['omnichannel'] },
	),

	entityDropdown({ resource: ['entity'], operation: ['getStructure'] }),
	entityDropdown({ resource: ['record', 'repeatableGroup', 'calendar'] }),
	entityDropdown({ resource: ['file'], operation: ['upload'] }),
	entityDropdown({ resource: ['communication'], operation: ['sendSms'] }),

	{
		displayName: 'Record ID',
		name: 'instanceId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['record'],
				operation: ['get', 'update', 'archive', 'unarchive', 'getHistory'],
			},
		},
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to flatten field groups into one object',
		displayOptions: { show: { resource: ['record'], operation: ['get', 'getAll'] } },
	},
	{
		displayName: 'Create Mode',
		name: 'createMode',
		type: 'options',
		options: [
			{ name: 'Field Builder', value: 'builder' },
			{ name: 'Raw JSON', value: 'json' },
		],
		default: 'builder',
		displayOptions: { show: { resource: ['record'], operation: ['create'] } },
	},
	{
		displayName: 'Fields',
		name: 'createFields',
		placeholder: 'Add Field',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: { show: { resource: ['record'], operation: ['create'], createMode: ['builder'] } },
		options: [
			{
				displayName: 'Field',
				name: 'field',
				values: [
					{
						displayName: 'Group Name or ID',
						name: 'groupDataName',
						type: 'options',
						description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
						typeOptions: { loadOptionsMethod: 'getGroups', loadOptionsDependsOn: ['entityDataName'] },
						default: '',
					},
					{
						displayName: 'Field Name or ID',
						name: 'fieldDataName',
						type: 'options',
						description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
						typeOptions: {
							loadOptionsMethod: 'getFields',
							loadOptionsDependsOn: ['entityDataName', 'createFields.field.groupDataName'],
						},
						default: '',
					},
					{
						displayName: 'Value',
						name: 'value',
						type: 'string',
						default: '',
						description: 'Relation/select: related record _id. Dates: as the structure shows (often DD/MM/YYYY).',
					},
				],
			},
		],
	},
	{
		displayName: 'Form Data',
		name: 'formData',
		type: 'json',
		default: '[]',
		description: 'Form_data array: [{group_data_name, data:[{fld:value,...}]}]. For bulk, an array of those records.',
		displayOptions: { show: { resource: ['record'], operation: ['create'], createMode: ['json'] } },
	},
	{
		displayName: 'Bulk Create',
		name: 'bulkCreate',
		type: 'boolean',
		default: false,
		description: 'Whether to send bulk=1 (max 200 records). Use JSON form_data as an array of records.',
		displayOptions: { show: { resource: ['record'], operation: ['create'] } },
	},
	{
		displayName: 'Force Workflow Async',
		name: 'forceWorkflowAsync',
		type: 'boolean',
		default: false,
		description:
			'Whether to send force_workflow_async=1 so Origami workflows run async and do not fail the API write',
		displayOptions: {
			show: {
				resource: ['record', 'repeatableGroup'],
				operation: ['create', 'update', 'add'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		description: 'Whether to return all results or only up to a given limit',
		default: false,
		displayOptions: { show: { resource: ['record', 'invoice'], operation: ['getAll'] } },
	},
	{
		displayName: 'Max Records',
		name: 'maxRecords',
		type: 'number',
		default: 5000,
		typeOptions: { minValue: 1 },
		description: 'Safety cap for Return All. The output pane shows a warning if Origami had more rows.',
		displayOptions: { show: { resource: ['record', 'invoice'], operation: ['getAll'], returnAll: [true] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		description: 'Max number of results to return',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 500 },
		displayOptions: { show: { resource: ['record', 'invoice'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Skip',
		name: 'skip',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		description: 'Origami paging is limit:[skip,count]. The page parameter is ignored by the API.',
		displayOptions: { show: { resource: ['record', 'invoice'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Filter Mode',
		name: 'filterMode',
		type: 'options',
		options: [
			{ name: 'None', value: 'none' },
			{ name: 'Builder', value: 'builder' },
			{ name: 'Raw JSON', value: 'json' },
		],
		default: 'none',
		displayOptions: { show: { resource: ['record'], operation: ['getAll'] } },
	},
	{
		displayName: 'Combine Conditions',
		name: 'filterCombine',
		type: 'options',
		options: [
			{ name: 'AND', value: 'and' },
			{ name: 'OR (Andxor)', value: 'or' },
		],
		default: 'and',
		description: 'OR sends filter:{andxor:[[cond],[cond]]}. AND sends a flat list of triples.',
		displayOptions: { show: { resource: ['record'], operation: ['getAll'], filterMode: ['builder'] } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		placeholder: 'Add Condition',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: { show: { resource: ['record'], operation: ['getAll'], filterMode: ['builder'] } },
		options: [
			{
				displayName: 'Condition',
				name: 'condition',
				values: [
					{
						displayName: 'Field Name or ID',
						name: 'field',
						type: 'options',
						description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
						typeOptions: { loadOptionsMethod: 'getAllFields', loadOptionsDependsOn: ['entityDataName'] },
						default: '',
					},
					{
						displayName: 'Operator',
						name: 'operator',
						type: 'options',
						options: ['=', '!=', '>', '<', '>=', '<=', 'in', 'like'].map((op) => ({ name: op, value: op })),
						default: '=',
					},
					{ displayName: 'Value', name: 'value', type: 'string', default: '' },
				],
			},
		],
	},
	{
		displayName: 'Filter JSON',
		name: 'filterJson',
		type: 'json',
		default: '[["fld_x","=","value"]]',
		displayOptions: { show: { resource: ['record'], operation: ['getAll'], filterMode: ['json'] } },
	},
	{
		displayName: 'Include Archived',
		name: 'withArchive',
		type: 'boolean',
		default: false,
		description:
			'Whether to include archived records. Off sends with_archive=0 (exclude). On leaves the flag unset so Origami returns archived too.',
		displayOptions: { show: { resource: ['record'], operation: ['getAll'] } },
	},
	{
		displayName: 'Normalized',
		name: 'normalized',
		type: 'boolean',
		default: true,
		description:
			'Whether to send normalized=1 (flat values). Off keeps nested values including phone normalize country codes.',
		displayOptions: { show: { resource: ['record'], operation: ['get', 'getAll'] } },
	},
	{
		displayName: 'Return Fields',
		name: 'returnFields',
		type: 'string',
		default: '',
		placeholder: 'fld_a,fld_b',
		description: 'Comma-separated field_data_name list. Maps to return_fields.',
		displayOptions: { show: { resource: ['record'], operation: ['get', 'getAll'] } },
	},
	{
		displayName: 'Return Groups',
		name: 'returnGroups',
		type: 'string',
		default: '',
		placeholder: 'g_1138',
		description: 'Comma-separated group_data_name list. Maps to return_groups.',
		displayOptions: { show: { resource: ['record'], operation: ['get', 'getAll'] } },
	},
	{
		displayName: 'Order By',
		name: 'orderBy',
		type: 'string',
		default: '',
		placeholder: 'fld_x,desc',
		description: 'Sort as field,asc|desc or JSON ["fld_x","desc"]. Maps to orderby. _id sorts by insertTimestamp.',
		displayOptions: { show: { resource: ['record'], operation: ['getAll'] } },
	},
	{
		displayName: 'Inner Order By',
		name: 'innerOrderBy',
		type: 'json',
		default: '[]',
		description: 'Optional inner_orderby JSON array-of-arrays for nested sorts',
		displayOptions: { show: { resource: ['record'], operation: ['getAll'] } },
	},
	{
		displayName: 'Skip Formula Recalc',
		name: 'dontRecalcFormula',
		type: 'boolean',
		default: false,
		description: 'Whether to send dont_recalc_formula=1 on reads',
		displayOptions: { show: { resource: ['record'], operation: ['get', 'getAll'] } },
	},
	{
		displayName: 'With Comments',
		name: 'withComments',
		type: 'boolean',
		default: false,
		description: 'Whether to send with_comments=1 when the entity supports comments',
		displayOptions: { show: { resource: ['record'], operation: ['get', 'getAll'] } },
	},
	{
		displayName: 'Use Protected Endpoint',
		name: 'useProtected',
		type: 'boolean',
		default: false,
		description: 'Whether to use instance_data_protected for users/groups (SUPA API user)',
		displayOptions: { show: { resource: ['record'], operation: ['getAll', 'get'] } },
	},
	{
		displayName: 'Update Mode',
		name: 'updateMode',
		type: 'options',
		options: [
			{ name: 'Field Builder', value: 'builder' },
			{ name: 'Raw JSON', value: 'json' },
		],
		default: 'builder',
		displayOptions: { show: { resource: ['record'], operation: ['update'] } },
	},
	{
		displayName: 'Fields',
		name: 'updateFields',
		placeholder: 'Add Field',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: { show: { resource: ['record'], operation: ['update'], updateMode: ['builder'] } },
		options: [
			{
				displayName: 'Field',
				name: 'field',
				values: [
					{
						displayName: 'Field Name or ID',
						name: 'fieldDataName',
						type: 'options',
						description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
						typeOptions: { loadOptionsMethod: 'getWritableFields', loadOptionsDependsOn: ['entityDataName'] },
						default: '',
					},
					{ displayName: 'Value', name: 'value', type: 'string', default: '' },
					{
						displayName: 'Group Index',
						name: 'groupIndex',
						type: 'number',
						default: 0,
						description: '0 for non-repeatable rows',
					},
				],
			},
		],
	},
	{
		displayName: 'Field Triples',
		name: 'updateFieldsJson',
		type: 'json',
		default: '[["fld_x","value",0]]',
		displayOptions: { show: { resource: ['record'], operation: ['update'], updateMode: ['json'] } },
	},
	{
		displayName: 'Record IDs',
		name: 'deleteIds',
		type: 'string',
		default: '',
		description: 'Comma-separated _id values',
		displayOptions: { show: { resource: ['record'], operation: ['delete'] } },
	},

	{
		displayName: 'Group Name or ID',
		name: 'groupDataName',
		type: 'options',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getRepeatableGroups', loadOptionsDependsOn: ['entityDataName'] },
		required: true,
		default: '',
		displayOptions: { show: { resource: ['repeatableGroup'] } },
	},
	{
		displayName: 'Record ID',
		name: 'instanceId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['repeatableGroup'] } },
	},
	{
		displayName: 'Group Data',
		name: 'groupData',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['repeatableGroup'], operation: ['add'] } },
	},
	{
		displayName: 'Row Index',
		name: 'groupIndex',
		type: 'number',
		default: 0,
		displayOptions: { show: { resource: ['repeatableGroup'], operation: ['remove'] } },
	},
	{
		displayName: 'Origami file fields hold one file. Uploading replaces the file currently in the field.',
		name: 'uploadNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['file'], operation: ['upload'] } },
	},
	{
		displayName: 'Record ID',
		name: 'instanceId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['file'], operation: ['upload'] } },
	},
	{
		displayName: 'Field Name or ID',
		name: 'fieldDataName',
		type: 'options',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getFileFields', loadOptionsDependsOn: ['entityDataName'] },
		default: '',
		displayOptions: { show: { resource: ['file'], operation: ['upload'] } },
	},
	{
		displayName: 'Input Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		required: true,
		displayOptions: { show: { resource: ['file'], operation: ['upload'] } },
	},
	{
		displayName: 'File ID',
		name: 'fileId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['file'], operation: ['download'] } },
	},

	{
		displayName: 'Invoice Type',
		name: 'invoiceType',
		type: 'options',
		options: [...INVOICE_TYPES],
		default: 'deal_invoice',
		displayOptions: { show: { resource: ['invoice'] } },
	},
	{
		displayName: 'Invoice ID',
		name: 'invoiceId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['invoice'], operation: ['get'] } },
	},
	{
		displayName: 'Create Mode',
		name: 'invoiceCreateMode',
		type: 'options',
		options: [
			{ name: 'Builder', value: 'builder' },
			{ name: 'Raw JSON', value: 'json' },
		],
		default: 'builder',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
	},
	{
		displayName: 'Customer ID',
		name: 'invoiceCustomerId',
		type: 'string',
		default: '',
		description: 'Record ID from the customer entity mapped to this company. Wrong catalog returns an item/customer not found error.',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceCreateMode: ['builder'] } },
	},
	{
		displayName: 'Date',
		name: 'invoiceDate',
		type: 'string',
		default: '',
		placeholder: 'DD/MM/YYYY',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceCreateMode: ['builder'] } },
	},
	{
		displayName: 'Currency',
		name: 'invoiceCurrency',
		type: 'options',
		options: [
			{ name: 'NIS', value: 'NIS' },
			{ name: 'USD', value: 'USD' },
			{ name: 'EURO', value: 'EURO' },
		],
		default: 'NIS',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceCreateMode: ['builder'] } },
	},
	{
		displayName: 'Company Index',
		name: 'invoiceCompanyIndex',
		type: 'options',
		options: ['0', '1', '2', '3', '4', '5'].map((v) => ({ name: v, value: v })),
		default: '0',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceCreateMode: ['builder'] } },
	},
	{
		displayName: 'Items',
		name: 'invoiceItems',
		placeholder: 'Add Item',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceCreateMode: ['builder'] } },
		options: [
			{
				displayName: 'Item',
				name: 'item',
				values: [
					{
						displayName: 'Charge VAT',
						name: 'chargeVat',
						type: 'boolean',
						default: true,
						description: 'Whether Origami adds Tax Percent on top of Unit Price (include_tax=1). Off issues the line with no VAT. Unit Price is always before VAT. Origami computes line price, tax and total.',
					},
					{
						displayName: 'Item ID',
						name: 'itemId',
						type: 'string',
						default: '',
					},
					{
						displayName: 'Quantity',
						name: 'quantity',
						type: 'number',
						default: 1
					},
					{
						displayName: 'Tax Percent',
						name: 'taxPercent',
						type: 'number',
						default: 18
					},
					{
						displayName: 'Unit Price',
						name: 'unitPrice',
						type: 'number',
						default: 0
					},
				],
			},
		],
	},
	{
		displayName: 'Attach Invoice ID',
		name: 'attachInvoiceId',
		type: 'string',
		default: '',
		description: 'Parent document for refund_invoice. Sent as {instance_id, text}.',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceType: ['refund_invoice'] } },
	},
	{
		displayName: 'Attach Type',
		name: 'attachType',
		type: 'options',
		options: [
			{ name: 'Deal Invoice', value: 'deal_invoice' },
			{ name: 'Manual (No Parent)', value: 'manual' },
			{ name: 'Receipt', value: 'receipt' },
			{ name: 'Tax Invoice', value: 'tax_invoice' },
			{ name: 'Tax Receipt', value: 'tax_receipt' },
		],
		default: 'tax_invoice',
		description: 'Maps to attach_type on refund_invoice. manual = standalone credit.',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceType: ['refund_invoice'] } },
	},
	{
		displayName: 'Round Total',
		name: 'roundTotal',
		type: 'boolean',
		default: false,
		description: 'Whether to send round_total=1 so Origami rounds the document total',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
	},
	{
		displayName: 'Cash Amount',
		name: 'invoiceCashAmount',
		type: 'number',
		default: 0,
		description: 'Adds origami_invoices_cash when > 0. Required for tax_receipt/receipt so payments match items.',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceCreateMode: ['builder'] } },
	},
	{
		displayName: 'External Unique ID',
		name: 'externalUniqueId',
		type: 'string',
		default: '',
		description: 'Optional idempotency key (external_unique_id). Ignored until Origami v6.3.6+ ships it.',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
	},
	{
		displayName: 'Saved Draft ID',
		name: 'savedId',
		type: 'string',
		default: '',
		description: 'Issue a previously saved draft (saved_id). Leave empty for a new document.',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
	},
	{
		displayName: 'Form Data',
		name: 'invoiceFormData',
		type: 'json',
		default:
			'[{"group_data_name":"origami_invoices_general_details","data":[{}]},{"group_data_name":"origami_invoices_items","data":[{}]}]',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'], invoiceCreateMode: ['json'] } },
	},

	{
		displayName: 'To (Comma-Separated)',
		name: 'emailList',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['communication'], operation: ['sendEmail'] } },
	},
	{
		displayName: 'Subject',
		name: 'emailSubject',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['communication'], operation: ['sendEmail'] } },
	},
	{
		displayName: 'HTML Body',
		name: 'emailBody',
		type: 'string',
		typeOptions: { rows: 5 },
		default: '',
		displayOptions: { show: { resource: ['communication'], operation: ['sendEmail'] } },
	},
	{
		displayName: 'BCC Sender',
		name: 'emailBcc',
		type: 'boolean',
		default: true,
		displayOptions: { show: { resource: ['communication'], operation: ['sendEmail'] } },
	},
	{
		displayName: 'Record ID',
		name: 'instanceId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['communication'], operation: ['sendSms'] } },
	},
	{
		displayName: 'Phones',
		name: 'phoneList',
		type: 'string',
		default: '',
		description: 'Comma-separated numbers',
		displayOptions: { show: { resource: ['communication'], operation: ['sendSms'] } },
	},
	{
		displayName: 'Message',
		name: 'smsMessage',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['communication'], operation: ['sendSms'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['communication'], operation: ['sendPush'] } },
	},
	{
		displayName: 'Text',
		name: 'pushText',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['communication'], operation: ['sendPush'] } },
	},
	{
		displayName: 'Duration (Minutes, 0 = Sticky)',
		name: 'pushDuration',
		type: 'number',
		default: 5,
		displayOptions: { show: { resource: ['communication'], operation: ['sendPush'] } },
	},

	{
		displayName: 'Message JSON',
		name: 'omniPayload',
		type: 'json',
		default: '{}',
		description: 'Body for omnichannel_external/api/new_message. Ingest only — there is no read API.',
		displayOptions: { show: { resource: ['omnichannel'] } },
	},
	{
		displayName: 'View ID',
		name: 'calendarViewId',
		type: 'string',
		default: '',
		description: 'Calendar view ID sent as view_id (also sent as ID)',
		displayOptions: { show: { resource: ['calendar'] } },
	},
	{
		displayName: 'Start',
		name: 'calendarStart',
		type: 'string',
		default: '',
		placeholder: '2026-09-01',
		description: 'Required by Origami. ISO date or datetime.',
		displayOptions: { show: { resource: ['calendar'] } },
	},
	{
		displayName: 'End',
		name: 'calendarEnd',
		type: 'string',
		default: '',
		placeholder: '2026-09-30',
		description: 'Required by Origami. ISO date or datetime.',
		displayOptions: { show: { resource: ['calendar'] } },
	},
	{
		displayName: 'View Payload JSON',
		name: 'calendarPayload',
		type: 'json',
		default: '{}',
		description: 'Extra body fields for calander_view_details',
		displayOptions: { show: { resource: ['calendar'] } },
	},
];
